apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sentinel-router-staging

namePrefix: staging-

commonLabels:
  environment: staging
  app.kubernetes.io/part-of: sentinel-router

bases:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml
  - config-patch.yaml

images:
  - name: sentinelrouter/sentinel-api
    newTag: staging-v1.0.0

replicas:
  - name: sentinel-api
    count: 2

configMapGenerator:
  - name: sentinel-config
    behavior: merge
    literals:
      - feature_validator_intelligence=true
      - feature_jito_bundles=true
      - ai_latency_target_ms=75
      - otel_service_name=sentinel-router-staging
