apiVersion: v2
name: sentinel-router
description: Production-grade MEV protection service for Solana with sub-50ms AI threat detection
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - solana
  - mev
  - blockchain
  - security
  - ai
maintainers:
  - name: Sentinel Router Team
    email: team@sentinel-router.io
home: https://sentinel-router.io
sources:
  - https://github.com/sentinel-router/sentinel-router
icon: https://sentinel-router.io/icon.png
dependencies: []
